# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(to='core.Disciplina'),
        ),
    ]
