# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170926_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='d_requisito',
            field=models.ManyToManyField(to='core.Disciplina'),
        ),
    ]
