# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170926_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(blank=True, to='core.Disciplina'),
        ),
    ]
