# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 20:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170928_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nascimento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
