# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aluno_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], default='masculino', max_length=50),
            preserve_default=False,
        ),
    ]
