# Generated by Django 2.0.1 on 2018-01-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aluno_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='d_requisito',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='credito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Credito'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Curso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(to='core.Disciplina'),
        ),
    ]
